apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-service
  labels:
    app: anomaly
    version: v0-1-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anomaly
  template:
    metadata:
      labels:
        app: anomaly
        version: v0-1-1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: anomaly
          image: anomaly:v0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-service
  labels:
    app: anomaly
spec:
  selector:
    app: anomaly
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
