apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-service
  labels:
    app: anomaly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly
  template:
    metadata:
      labels:
        app: anomaly
    spec:
      containers:
      - name: anomaly
        image: anomaly:v0.1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-service
spec:
  selector:
    app: anomaly
  ports:
  - port: 8000
    targetPort: 8000
