apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: anomaly-servicemonitor
  namespace: default
  labels:
    release: monitoring   # IMPORTANT: matches Prometheus Operator release label
spec:
  selector:
    matchLabels:
      app: anomaly
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http
