apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: anomaly-servicemonitor
  labels:
    release: prometheus  # adjust if your Prometheus Operator uses a different label
spec:
  selector:
    matchLabels:
      app: anomaly   # must match the label on your Service
  namespaceSelector:
    matchNames:
      - default      # ensure it looks into the "default" namespace
  endpoints:
    - port: http     # must match the port name in your Service
      path: /metrics
      interval: 15s
      scheme: http
